#!/bin/bash
# setup-mac-cron.sh
# Run once to install an hourly Jira sync cron job on your Mac.
# The job runs every hour, fetches from Jira, and pushes to Heroku.
#
# Usage:
#   cd ~/gsp-tracker
#   bash scripts/setup-mac-cron.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
LOG_FILE="$REPO_DIR/sync.log"
NODE_BIN="$(which node)"

echo "╔══════════════════════════════════════════════╗"
echo "║  GSP Sync — Mac Cron Setup                   ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "Repo:   $REPO_DIR"
echo "Node:   $NODE_BIN"
echo "Log:    $LOG_FILE"
echo ""

# Verify node is available
if [ -z "$NODE_BIN" ]; then
  echo "✗ Node.js not found. Install it from https://nodejs.org and re-run."
  exit 1
fi

# Prompt for PAT if not already set
if [ -z "$JIRA_PAT" ]; then
  echo -n "Enter your Jira PAT: "
  read -r JIRA_PAT
fi

if [ -z "$JIRA_PAT" ]; then
  echo "✗ JIRA_PAT is required."
  exit 1
fi

# Write a wrapper script with env vars baked in (so cron can find them)
WRAPPER="$REPO_DIR/scripts/run-sync.sh"
cat > "$WRAPPER" <<WRAPPER_EOF
#!/bin/bash
# Auto-generated by setup-mac-cron.sh — do not edit manually
export JIRA_PAT="$JIRA_PAT"
export JIRA_URL="https://jira.ringcentral.com"
export HEROKU_URL="https://gsp-release-tracker-ffa0c1ec9485.herokuapp.com"
export PATH="/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:\$PATH"

cd "$REPO_DIR"
echo "--- Sync started: \$(date) ---" >> "$LOG_FILE"
"$NODE_BIN" scripts/sync-local.js >> "$LOG_FILE" 2>&1
echo "--- Sync ended:   \$(date) ---" >> "$LOG_FILE"
WRAPPER_EOF
chmod +x "$WRAPPER"
echo "✓ Wrapper script written: $WRAPPER"

# Install cron job (runs every hour at :05 past the hour)
CRON_ENTRY="5 * * * * $WRAPPER"

# Check if already installed
if crontab -l 2>/dev/null | grep -q "run-sync.sh"; then
  echo "✓ Cron job already installed — updating..."
  (crontab -l 2>/dev/null | grep -v "run-sync.sh"; echo "$CRON_ENTRY") | crontab -
else
  (crontab -l 2>/dev/null; echo "$CRON_ENTRY") | crontab -
fi

echo "✓ Cron job installed (runs every hour at :05)"
echo ""
echo "────────────────────────────────────────────────"
echo "  Running first sync now to verify…"
echo "────────────────────────────────────────────────"
echo ""
bash "$WRAPPER"

echo ""
echo "────────────────────────────────────────────────"
echo "  Setup complete!"
echo ""
echo "  Cron schedule:  every hour at :05"
echo "  Log file:       $LOG_FILE"
echo "  View logs:      tail -f $LOG_FILE"
echo "  Remove cron:    crontab -l | grep -v run-sync.sh | crontab -"
echo "────────────────────────────────────────────────"
